In [ ]:
functions to create array
manual 
auto
attributes and functions-1d, 2D
indexing and slicing-1d , 2d
condition based indexing and slicing
operations on 1d array-arith,log,tri,agg
operations on 2d array
arithmetic functions-agg, stat
concat-1d 2d
stack,hstack,vstack,dstack,block
split-hsplit.vsplit,split,array aplit
iteration-for loop,nditer()

In [ ]:
numpy
pandas
seaborn
matplotlib
plotly

In [1]:
import numpy as np

In [ ]:
#create a simple array

In [3]:
np.array(12)

array(12)

In [6]:
a=np.array(1)
a

array(1)

In [7]:
np.array(23.45)

array(23.45)

In [8]:
np.array(8j)

array(0.+8.j)

In [3]:
np.array('12345657')

array('12345657', dtype='<U8')

In [10]:
np.array('dhdhhdhh')

array('dhdhhdhh', dtype='<U8')

In [11]:
np.array((1,2,3,4))

array([1, 2, 3, 4])

In [12]:
np.array([1,2,3,4,5])# list-1D

array([1, 2, 3, 4, 5])

In [13]:
np.array([[1,2],[3,4],[5,6]])#list of list ==> 2D array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
np.array([[[1,2,3],[4,5,6],[7,8,9]]])# 3d array

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [16]:
np.array({1:234,4:4456})

array({1: 234, 4: 4456}, dtype=object)

In [19]:
np.array(False)

array(False)

In [14]:
np.array({1,2,3.676,4,5,0.67,6+7j})
         

array({0.67, 1, 2, 3.676, 4, 5, (6+7j)}, dtype=object)

In [15]:
np.array({1,8,6,4,3,0.5,0.1,9})

         

array({0.5, 1, 0.1, 3, 4, 6, 8, 9}, dtype=object)

In [27]:
# automatic methods

In [37]:
np.zeros(3)  # 1D zero matrix, float64 is a default data

array([0., 0., 0.])

In [31]:
np.zeros(3,dtype=np.int64)

array([0, 0, 0], dtype=int64)

In [32]:
np.zeros(3,dtype=np.complex128)

array([0.+0.j, 0.+0.j, 0.+0.j])

In [35]:
np.zeros([3,2])# 2d array

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [16]:
np.zeros([2,3,3])# 3d array zero matrix

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [39]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [40]:
np.zeros([3,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [18]:
np.zeros([3,3,3])

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [42]:
# unity matrix

In [43]:
a=np.ones(3)

In [44]:
a

array([1., 1., 1.])

In [47]:
np.ones(4)

array([1., 1., 1., 1.])

In [48]:
np.ones([3,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [49]:
np.ones([3,4,5])

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [50]:
np.array([[[[1,2,3,4],[2,3,8,6],[4,5,7,5]]]])


array([[[[1, 2, 3, 4],
         [2, 3, 8, 6],
         [4, 5, 7, 5]]]])

In [51]:
# random number generation in  numpy

In [5]:
np.random.randint(0,10,3)

array([6, 7, 0])

In [6]:
abc=np.random.randint(-5,5,10)

In [7]:
abc

array([-2, -3,  0, -5, -1, -1, -4, -3, -4, -1])

In [9]:
np.random.rand(3)# 0 and 1 1D

array([0.03863452, 0.1356757 , 0.14644706])

In [76]:
np.random.rand(3,2) 2D

array([[0.94088303, 0.24390087],
       [0.18463195, 0.4350347 ],
       [0.32763289, 0.18635592]])

In [79]:
np.random.rand(3,3,3) # 3D random matrix

array([[[0.52556752, 0.29345512, 0.04524807],
        [0.60678936, 0.89671622, 0.392905  ],
        [0.24472009, 0.54548504, 0.69316171]],

       [[0.31739624, 0.19732086, 0.00166995],
        [0.94388053, 0.81145949, 0.08179648],
        [0.56405376, 0.85589803, 0.11163418]],

       [[0.16939201, 0.93363193, 0.26208519],
        [0.83670034, 0.68760309, 0.15505665],
        [0.44460202, 0.95406443, 0.20519061]]])

In [11]:
np.random.randn(3) #1D

array([-1.64352893,  0.62126422,  0.30574995])

In [12]:
np.random.randn(3,3)# 2D

array([[ 1.82233937, -0.23010219,  0.44643581],
       [ 2.39422592, -0.27726983,  1.70553747],
       [ 0.86162101,  0.72336727, -0.22261006]])

In [13]:
np.random.randn(3,3,3)

array([[[-0.25237873, -2.65538483, -0.08341636],
        [-0.33691396,  1.40019328, -2.23544809],
        [ 0.71017681, -0.37300413,  0.45079353]],

       [[-0.52642705,  1.1277827 , -1.90919345],
        [ 0.07280035, -0.82678844, -2.22393556],
        [-0.91766287, -0.62099438, -0.90066586]],

       [[ 0.39358814,  1.4931145 ,  0.68578749],
        [-0.46053175,  0.39347805, -0.42238493],
        [-0.80894868,  1.14848061,  0.62816297]]])

In [22]:
np.random.random(3) # between 0 and 1 where 1 is exclusive, half interval

array([0.71733679, 0.49294464, 0.44600039])

In [23]:
np.random.random([2,2])# 2D

array([[0.19690184, 0.11661355],
       [0.31477847, 0.90809932]])

In [24]:
np.random.random([3,3,4])# 3D

array([[[0.60345572, 0.95353626, 0.25061809, 0.33484317],
        [0.27101255, 0.39370742, 0.71992454, 0.57464874],
        [0.98242696, 0.46754172, 0.80146831, 0.89219432]],

       [[0.63457693, 0.83361824, 0.22229665, 0.25205742],
        [0.38892601, 0.63693432, 0.42960011, 0.07035549],
        [0.7113343 , 0.24492544, 0.47726797, 0.44336734]],

       [[0.24411673, 0.27734591, 0.56972232, 0.7452183 ],
        [0.07955376, 0.67511385, 0.21444994, 0.39891172],
        [0.97266917, 0.40655439, 0.6187942 , 0.3463378 ]]])

In [25]:
Summary:random
1.randint
2.rand-0 and 1
3.randn-normalization--ve and +ve as close as possible to 0
4.random-0 and 1 but 1 is not included==>half interval 

SyntaxError: invalid syntax (<ipython-input-25-c38c885fab5f>, line 2)

In [94]:
list(range(1,8))

[1, 2, 3, 4, 5, 6, 7]

In [1]:
list(range(1,8,2))

[1, 3, 5, 7]

In [26]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [28]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [29]:
np.arange(1.2,11.2,2)

array([1.2, 3.2, 5.2, 7.2, 9.2])

In [30]:
np.arange(-11.2,-1.2,2)

array([-11.2,  -9.2,  -7.2,  -5.2,  -3.2])

In [31]:
np.arange(-11.2,-1.2,2.4)

array([-11.2,  -8.8,  -6.4,  -4. ,  -1.6])

In [32]:
np.arange(0,21)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [33]:
np.arange(0,21,dtype=np.float64)
         

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20.])

In [34]:
np.arange(0,21,dtype=np.complex128)

array([ 0.+0.j,  1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j,  5.+0.j,  6.+0.j,
        7.+0.j,  8.+0.j,  9.+0.j, 10.+0.j, 11.+0.j, 12.+0.j, 13.+0.j,
       14.+0.j, 15.+0.j, 16.+0.j, 17.+0.j, 18.+0.j, 19.+0.j, 20.+0.j])

In [35]:
# attributes of an array

In [36]:
abc=np.array([[1,2,3],[4,5,6]])

In [58]:
abc

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
abc.shape

(2, 3)

In [60]:
abc.shape[0]

2

In [39]:
abc.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [40]:
abc.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [41]:
abc.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [61]:
qwe=np.arange(11)

In [62]:
qwe

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
qwe.reshape(1,11)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [64]:
qwe.reshape(11,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [65]:
abc

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
abc.ndim

2

In [53]:
type(abc)

numpy.ndarray

In [54]:
abc.size# total no of elements in your array

6

In [132]:
abc.itemsize # how much memory in byte is occupied by a single data element.

4

In [133]:
id(abc) # memory location

2253826304560

In [134]:
len(abc) # indicates no of rows

2

In [56]:
abc

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# indexing and slicing in array

In [140]:
a=np.array([1,2,3,4,5,6])

In [151]:
a[-5:-1:2]

array([2, 4])

In [152]:
# indexing and slicing of a 2D array

In [7]:
qwe=np.random.rand(3,3)

In [8]:
qwe

array([[0.0655807 , 0.00700008, 0.55992888],
       [0.36062694, 0.15108099, 0.01843929],
       [0.38273617, 0.2148178 , 0.47188509]])

In [9]:
qwe[0,0]

0.0655807013532832

In [10]:
np.round(qwe[0,0],3)

0.066

In [11]:
qwe

array([[0.0655807 , 0.00700008, 0.55992888],
       [0.36062694, 0.15108099, 0.01843929],
       [0.38273617, 0.2148178 , 0.47188509]])

In [12]:
qwe[2]# for

array([0.38273617, 0.2148178 , 0.47188509])

In [13]:
qwe[-1]#rev

array([0.38273617, 0.2148178 , 0.47188509])

In [14]:
qwe

array([[0.0655807 , 0.00700008, 0.55992888],
       [0.36062694, 0.15108099, 0.01843929],
       [0.38273617, 0.2148178 , 0.47188509]])

In [15]:
qwe[ : ,1  ]

array([0.00700008, 0.15108099, 0.2148178 ])

In [16]:
qwe[ : ,1:2  ]

array([[0.00700008],
       [0.15108099],
       [0.2148178 ]])

In [17]:
qwe

array([[0.0655807 , 0.00700008, 0.55992888],
       [0.36062694, 0.15108099, 0.01843929],
       [0.38273617, 0.2148178 , 0.47188509]])

In [18]:
qwe[:,0:2]# for

array([[0.0655807 , 0.00700008],
       [0.36062694, 0.15108099],
       [0.38273617, 0.2148178 ]])

In [19]:
qwe[:,-3:-1]# rev

array([[0.0655807 , 0.00700008],
       [0.36062694, 0.15108099],
       [0.38273617, 0.2148178 ]])

In [20]:
qwe

array([[0.0655807 , 0.00700008, 0.55992888],
       [0.36062694, 0.15108099, 0.01843929],
       [0.38273617, 0.2148178 , 0.47188509]])

In [21]:
qwe[:,0:-1]

array([[0.0655807 , 0.00700008],
       [0.36062694, 0.15108099],
       [0.38273617, 0.2148178 ]])

In [174]:
qwe

array([[0.24499187, 0.17823536, 0.87786834],
       [0.84266424, 0.2241412 , 0.33459833],
       [0.44107032, 0.82093334, 0.58298877]])

In [179]:
# condition based indexing and slicing

In [176]:
b=np.array([1,2,3,4,5,6,7])

In [177]:
b

array([1, 2, 3, 4, 5, 6, 7])

In [178]:
b>4

array([False, False, False, False,  True,  True,  True])

In [185]:
b[b>=4]

array([4, 5, 6, 7])

In [186]:
b[b!=4]

array([1, 2, 3, 5, 6, 7])