In [ ]:
# identity matrix


In [6]:
import numpy as np
np.eye(3) # symmetrical identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [2]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [3]:
# operations on numpy arrays

In [7]:
abc=np.arange(10)

In [5]:
abc

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
qwe=np.arange(11,21)

In [7]:
qwe

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [8]:
abc

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a=[1,2,3]
a*2

[1, 2, 3, 1, 2, 3]

In [27]:
abc+2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [29]:
abc+=2

In [30]:
abc

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
abc

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
abc-3

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [19]:
abc*3

array([ 6,  9, 12, 15, 18, 21, 24, 27, 30, 33])

In [15]:
abc/3

array([0.66666667, 1.        , 1.33333333, 1.66666667, 2.        ,
       2.33333333, 2.66666667, 3.        , 3.33333333, 3.66666667])

In [31]:
abc

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [32]:
abc//3

array([0, 1, 1, 1, 2, 2, 2, 3, 3, 3], dtype=int32)

In [33]:
abc%3

array([2, 0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int32)

In [34]:
abc**2

array([  4,   9,  16,  25,  36,  49,  64,  81, 100, 121], dtype=int32)

In [35]:
np.power(abc,2)

array([  4,   9,  16,  25,  36,  49,  64,  81, 100, 121], dtype=int32)

In [36]:
abc

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [37]:
abc.sum()

65

In [38]:
sum(abc)

65

In [39]:
np.sum(abc)

65

In [45]:
abc

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [41]:
qwe

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [48]:
abc+qwe

array([13, 15, 17, 19, 21, 23, 25, 27, 29, 31])

In [46]:
qwe1=np.array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [47]:
abc+qwe1

ValueError: operands could not be broadcast together with shapes (10,) (9,) 

In [49]:
abc-qwe

array([-9, -9, -9, -9, -9, -9, -9, -9, -9, -9])

In [50]:
abc*qwe

array([ 22,  36,  52,  70,  90, 112, 136, 162, 190, 220])

In [51]:
abc/qwe

array([0.18181818, 0.25      , 0.30769231, 0.35714286, 0.4       ,
       0.4375    , 0.47058824, 0.5       , 0.52631579, 0.55      ])

In [52]:
abc//qwe

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [53]:
abc%qwe

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int32)

In [54]:
abc

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [55]:
abc.min()

2

In [56]:
min(abc)

2

In [57]:
np.min(abc)

2

In [58]:
qwe

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [59]:
qwe.max()

20

In [60]:
max(qwe)

20

In [61]:
np.max(qwe)

20

In [62]:
qwe

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [63]:
np.mean(qwe)

15.5

In [64]:
np.median(qwe)

15.5

In [65]:
abc

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [66]:
np.square(abc)

array([  4,   9,  16,  25,  36,  49,  64,  81, 100, 121], dtype=int32)

In [67]:
abc**2

array([  4,   9,  16,  25,  36,  49,  64,  81, 100, 121], dtype=int32)

In [68]:
np.power(abc,2)

array([  4,   9,  16,  25,  36,  49,  64,  81, 100, 121], dtype=int32)

In [69]:
pow(abc,2)

array([  4,   9,  16,  25,  36,  49,  64,  81, 100, 121], dtype=int32)

In [70]:
qwe

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [71]:
np.sqrt(qwe)

array([3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595])

In [72]:
qwe**0.5

array([3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595])

In [73]:
np.power(qwe,0.5)

array([3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595])

In [74]:
pow(qwe,0.5)

array([3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595])

In [75]:
abc

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [76]:
np.sin(abc)

array([ 0.90929743,  0.14112001, -0.7568025 , -0.95892427, -0.2794155 ,
        0.6569866 ,  0.98935825,  0.41211849, -0.54402111, -0.99999021])

In [77]:
np.cos(abc)

array([-0.41614684, -0.9899925 , -0.65364362,  0.28366219,  0.96017029,
        0.75390225, -0.14550003, -0.91113026, -0.83907153,  0.0044257 ])

In [78]:
# values are calculated as a radian not as a degree

In [79]:
qwe

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [80]:
np.log(qwe)

array([2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227])

In [81]:
np.log10(qwe)

array([1.04139269, 1.07918125, 1.11394335, 1.14612804, 1.17609126,
       1.20411998, 1.23044892, 1.25527251, 1.2787536 , 1.30103   ])

In [82]:
np.log2(qwe)

array([3.45943162, 3.5849625 , 3.70043972, 3.80735492, 3.9068906 ,
       4.        , 4.08746284, 4.169925  , 4.24792751, 4.32192809])

In [83]:
abc

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [84]:
abc.argmax() # returns the location of the highest value

9

In [85]:
abc.argmin()# returns the location of the lowest value

0

In [86]:
np.degrees(abc)

array([114.59155903, 171.88733854, 229.18311805, 286.47889757,
       343.77467708, 401.07045659, 458.3662361 , 515.66201562,
       572.95779513, 630.25357464])

In [87]:
np.degrees(qwe)

array([ 630.25357464,  687.54935416,  744.84513367,  802.14091318,
        859.4366927 ,  916.73247221,  974.02825172, 1031.32403124,
       1088.61981075, 1145.91559026])

In [88]:
# stack

In [5]:
abc

NameError: name 'abc' is not defined

In [90]:
qwe

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [100]:
np.hstack([abc,qwe])

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [92]:
np.vstack([abc,qwe])

array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [11]:
np.stack([abc,qwe],axis=0)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [94]:
abc

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [95]:
qwe

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [13]:
np.stack([abc,qwe],axis=1)

array([[ 0, 11],
       [ 1, 12],
       [ 2, 13],
       [ 3, 14],
       [ 4, 15],
       [ 5, 16],
       [ 6, 17],
       [ 7, 18],
       [ 8, 19],
       [ 9, 20]])

In [9]:
abc

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
qwe

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [11]:
np.hsplit(abc,2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [84]:
np.hsplit(abc,3)

ValueError: array split does not result in an equal division

In [12]:
a1=np.array([[1,2,3],[4,5,6]])
b1=np.array([[7,8,9],[10,11,12]])

In [13]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
b1

array([[ 7,  8,  9],
       [10, 11, 12]])

In [15]:
np.vsplit(a1,2)#row

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [17]:
np.hsplit(a1,3)#column

[array([[1],
        [4]]),
 array([[2],
        [5]]),
 array([[3],
        [6]])]

In [28]:
abc

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
qwe

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [18]:
np.vsplit(abc,2) # for 1D arrays

ValueError: vsplit only works on arrays of 2 or more dimensions

In [31]:
# vsplit only with 2D or higher dimensional data

In [32]:
q1=np.array([1])
q2=np.array([2])
q3=np.array([3])
q4=np.array([4])

In [115]:
np.block([[q1,q3],[q2,q4]]) # numpy arranges the data in rows

array([[1, 3],
       [2, 4]])

In [33]:
pol=np.random.randn(2,3,3)

In [34]:
pol

array([[[-1.71502368,  0.13751565,  0.31689416],
        [-0.85611683,  1.05187958,  0.0589661 ],
        [ 0.81590421,  0.64836337, -1.17220127]],

       [[ 0.50462509,  1.34420733,  1.34782959],
        [ 0.98232031,  0.65790444,  0.36144515],
        [ 1.15903161,  1.77712278,  0.21465008]]])

In [35]:
np.dsplit(pol,3) # depth split 3D arrays, dividing in to equal parts

[array([[[-1.71502368],
         [-0.85611683],
         [ 0.81590421]],
 
        [[ 0.50462509],
         [ 0.98232031],
         [ 1.15903161]]]),
 array([[[0.13751565],
         [1.05187958],
         [0.64836337]],
 
        [[1.34420733],
         [0.65790444],
         [1.77712278]]]),
 array([[[ 0.31689416],
         [ 0.0589661 ],
         [-1.17220127]],
 
        [[ 1.34782959],
         [ 0.36144515],
         [ 0.21465008]]])]

In [112]:
# iteration over numpy arrays

In [19]:
abc=np.arange(1,11)

In [20]:
abc


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
for data in abc:
    print(data**2)

1
4
9
16
25
36
49
64
81
100


In [122]:
abc

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [123]:
qwe

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [124]:
for data in zip(abc,qwe):
    print(data)

(1, 11)
(2, 12)
(3, 13)
(4, 14)
(5, 15)
(6, 16)
(7, 17)
(8, 18)
(9, 19)
(10, 20)


In [125]:
z=np.random.randn(2,2)

In [126]:
z

array([[ 0.41506734,  0.78849819],
       [-1.03434895,  0.04191165]])

In [127]:
p=np.random.randn(2,2)

In [128]:
p

array([[-2.10598369,  0.9158731 ],
       [-0.64019261, -0.68290075]])

In [129]:
for data in p:
    print(data)

[-2.10598369  0.9158731 ]
[-0.64019261 -0.68290075]


In [130]:
for row in p:
    for data in row:
        print(data)

-2.1059836850227596
0.9158730967868941
-0.6401926093118337
-0.682900754041613


In [131]:
p

array([[-2.10598369,  0.9158731 ],
       [-0.64019261, -0.68290075]])

In [132]:
for data in np.nditer(p):
    print(data) # faster

-2.1059836850227596
0.9158730967868941
-0.6401926093118337
-0.682900754041613


In [133]:
#please remember

In [134]:
axis=0
axis=1 is function specific

SyntaxError: invalid syntax (<ipython-input-134-e69f02a8b7f5>, line 2)

In [135]:
li=[1,2]

In [132]:
li.insert(0,'shambhvi')

In [133]:
li

['shambhvi', 1, 2]

In [36]:
a=np.array([[1,2],[3,4]])
b=np.array([[4,5],[5,6]])

In [37]:
a

array([[1, 2],
       [3, 4]])

In [38]:
b

array([[4, 5],
       [5, 6]])

In [39]:
a+b

array([[ 5,  7],
       [ 8, 10]])

In [40]:
a

array([[1, 2],
       [3, 4]])

In [41]:
np.append(a,2)

array([1, 2, 3, 4, 2])

In [144]:
np.nan

nan

In [42]:
bangalore_temp_last_week=np.array([33,31,29,np.nan,29,31,32])

In [43]:
bangalore_temp_last_week

array([33., 31., 29., nan, 29., 31., 32.])

In [148]:
# np.nan==> missing value

In [46]:
bangalore_temp_last_week.size

7

In [149]:
abc

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [142]:
abc[0:5]=100000

In [143]:
abc # broadcasting

array([100000, 100000, 100000, 100000, 100000,      6,      7,      8,
            9,     10])

In [144]:
abc

array([100000, 100000, 100000, 100000, 100000,      6,      7,      8,
            9,     10])

In [145]:
abc[0:5:2]=123

In [146]:
abc

array([   123, 100000,    123, 100000,    123,      6,      7,      8,
            9,     10])