In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings(action='ignore')

In [2]:
pd.Series(12)

0    12
dtype: int64

In [3]:
pd.Series(34.56)

0    34.56
dtype: float64

In [4]:
pd.Series(6+7j)

0    6.0+7.0j
dtype: complex128

In [5]:
string = "Hi" , "How" ,"are", "you", "?"

In [6]:
pd.Series(string)

0     Hi
1    How
2    are
3    you
4      ?
dtype: object

In [7]:
pd.Series((1,1.23,'apple','&',' '))

0        1
1     1.23
2    apple
3        &
4         
dtype: object

In [8]:
pd.Series([1,2,3,'apple',[1,2,3]])

0            1
1            2
2            3
3        apple
4    [1, 2, 3]
dtype: object

In [9]:
pd.Series({1:123,'a':'apple'})

1      123
a    apple
dtype: object

In [10]:
pd.Series({78,0.766,56})

TypeError: 'set' type is unordered

In [11]:
pd.Series(None)

Series([], dtype: float64)

In [12]:
pd.Series()

Series([], dtype: float64)

In [13]:
a=np.array([1,2,3,4,5,6,7])

In [14]:
pd.Series(a)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int32

In [15]:
pd.Series(np.arange(10))

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int32

In [16]:
pd.Series(np.random.rand(10))

0    0.613844
1    0.849310
2    0.538835
3    0.582936
4    0.354598
5    0.428359
6    0.857162
7    0.716062
8    0.733208
9    0.506353
dtype: float64

In [17]:
pd.Series(np.random.randn(10))

0    0.645132
1   -0.371395
2   -0.000430
3    0.861790
4   -0.594609
5    1.662674
6   -0.697198
7    0.697938
8   -0.068065
9   -1.491123
dtype: float64

In [18]:
pd.Series(np.random.randint(1,21,10))

0    15
1     2
2     7
3     9
4     8
5     6
6    18
7    10
8     6
9    20
dtype: int32

In [19]:
abc=pd.Series(np.random.randint(1,12,9))

In [20]:
abc

0    10
1     1
2    10
3     6
4    11
5     9
6     4
7     4
8     1
dtype: int32

In [21]:
abc[1]=100

In [22]:
abc # Series is mutable

0     10
1    100
2     10
3      6
4     11
5      9
6      4
7      4
8      1
dtype: int32

In [23]:
type(abc)

pandas.core.series.Series

In [24]:
abc

0     10
1    100
2     10
3      6
4     11
5      9
6      4
7      4
8      1
dtype: int32

In [25]:
abc.sum()

155

In [26]:
sum(abc)

155

In [27]:
abc.mean()

17.22222222222222

In [28]:
abc

0     10
1    100
2     10
3      6
4     11
5      9
6      4
7      4
8      1
dtype: int32

In [29]:
abc.median()

9.0

In [35]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
a.std()

2.8722813232690143

In [32]:
abc.std()

31.228103439761504

In [33]:
abc.var()

975.1944444444442

In [34]:
abc

0     10
1    100
2     10
3      6
4     11
5      9
6      4
7      4
8      1
dtype: int32

In [38]:
np.sqrt(abc)

0     2.645751
1    10.000000
2     2.236068
3     2.645751
4     1.732051
5     1.000000
6     2.645751
7     3.000000
8     1.414214
dtype: float64

In [39]:
np.sin(abc)

0    0.656987
1   -0.506366
2   -0.958924
3    0.656987
4    0.141120
5    0.841471
6    0.656987
7    0.412118
8    0.909297
dtype: float64

In [33]:
np.log10(abc)

0    0.602060
1    2.000000
2    0.845098
3    1.041393
4    0.602060
5    1.000000
6    0.903090
7    0.301030
8    1.000000
dtype: float64

In [40]:
abc

0      7
1    100
2      5
3      7
4      3
5      1
6      7
7      9
8      2
dtype: int32

In [41]:
abc**0.5

0     2.645751
1    10.000000
2     2.236068
3     2.645751
4     1.732051
5     1.000000
6     2.645751
7     3.000000
8     1.414214
dtype: float64

In [42]:
pow(abc,0.5)

0     2.645751
1    10.000000
2     2.236068
3     2.645751
4     1.732051
5     1.000000
6     2.645751
7     3.000000
8     1.414214
dtype: float64

In [37]:
s1=pd.Series(np.arange(16))
s2=pd.Series(np.arange(15,31))
print(s1)
print(s2)

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
dtype: int32
0     15
1     16
2     17
3     18
4     19
5     20
6     21
7     22
8     23
9     24
10    25
11    26
12    27
13    28
14    29
15    30
dtype: int32


In [38]:
result=s1+s2

In [39]:
result

0     15
1     17
2     19
3     21
4     23
5     25
6     27
7     29
8     31
9     33
10    35
11    37
12    39
13    41
14    43
15    45
dtype: int32

In [42]:
result[10]

35

In [43]:
result.loc[10]

35

In [44]:
result.iloc[10]

35

In [45]:
q=pd.Series({'a':'apple',12:144})

In [46]:
q

a     apple
12      144
dtype: object

In [47]:
q.loc['a']

'apple'

In [48]:
q[0]

KeyError: 0

In [49]:
q.iloc[0]

'apple'

In [50]:
result

0     15
1     17
2     19
3     21
4     23
5     25
6     27
7     29
8     31
9     33
10    35
11    37
12    39
13    41
14    43
15    45
dtype: int32

In [51]:
result[result!=25]

0     15
1     17
2     19
3     21
4     23
6     27
7     29
8     31
9     33
10    35
11    37
12    39
13    41
14    43
15    45
dtype: int32

In [52]:
result

0     15
1     17
2     19
3     21
4     23
5     25
6     27
7     29
8     31
9     33
10    35
11    37
12    39
13    41
14    43
15    45
dtype: int32

In [53]:
result.index # reading method

RangeIndex(start=0, stop=16, step=1)

In [54]:
result.values

array([15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45])

In [55]:
az=pd.Series([1,2,'a','apple',np.nan])

In [56]:
az

0        1
1        2
2        a
3    apple
4      NaN
dtype: object

In [57]:
az.isnull()

0    False
1    False
2    False
3    False
4     True
dtype: bool

In [58]:
az[az.isnull()]

4    NaN
dtype: object

In [59]:
az[az.isna()]

4    NaN
dtype: object

In [60]:
az=pd.Series([1,2,'a','apple',np.nan])

In [61]:
az

0        1
1        2
2        a
3    apple
4      NaN
dtype: object

In [62]:
az=az.fillna('shambhavi')

In [63]:
az

0            1
1            2
2            a
3        apple
4    shambhavi
dtype: object

In [68]:
az1=pd.Series([1,2,'a','apple',np.nan,np.nan])

In [69]:
az1

0        1
1        2
2        a
3    apple
4      NaN
5      NaN
dtype: object

In [70]:
az1.fillna('python')

0         1
1         2
2         a
3     apple
4    python
5    python
dtype: object

In [71]:
az1

0        1
1        2
2        a
3    apple
4      NaN
5      NaN
dtype: object

In [78]:
az1.loc[4]='python'

In [79]:
az1

0         1
1         2
2         a
3     apple
4    python
5       NaN
dtype: object

In [80]:
# pandas data frame

In [72]:
data=[23,34,56,78,89]
index=[0,1,2,3,4]
cols=['A','B','C','D','E']

In [73]:
abc=pd.DataFrame(data,index=['karnataka','Delhi','Maha','Kera','guj'],columns=['corona cases'])

In [74]:
abc

corona cases
karnataka            23
Delhi                34
Maha                 56
Kera                 78
guj                  89

In [75]:
data2=[[23,34,56,78,89],[100,200,300,400,500]] # list of list

In [14]:
final=pd.DataFrame(data2,index=['cured','affected'],columns=['Kar','Mah','Ker','Goa','Delhi'])

In [15]:
final

Kar  Mah  Ker  Goa  Delhi
cured      23   34   56   78     89
affected  100  200  300  400    500

In [89]:
tech={'python':[49,32,43,45,np.nan],'SQL':[23,45,67,89,np.nan]}

In [90]:
marks=pd.DataFrame(tech,index=['arti','amy','james','smith','poli'])

In [91]:
marks

python   SQL
arti     49.0  23.0
amy      32.0  45.0
james    43.0  67.0
smith    45.0  89.0
poli      NaN   NaN

In [92]:
abc

corona cases
karnataka            23
Delhi                34
Maha                 56
Kera                 78
guj                  89

In [93]:
abc.sample(2) # take random samples

corona cases
Delhi            34
guj              89

In [94]:
abc.head() # read the top 5 rows of your data frame

corona cases
karnataka            23
Delhi                34
Maha                 56
Kera                 78
guj                  89

In [95]:
abc.head(3)

corona cases
karnataka            23
Delhi                34
Maha                 56

In [96]:
abc.tail() # rows last 5

corona cases
karnataka            23
Delhi                34
Maha                 56
Kera                 78
guj                  89

In [97]:
abc.tail(2)

corona cases
Kera            78
guj             89

In [98]:
abc

corona cases
karnataka            23
Delhi                34
Maha                 56
Kera                 78
guj                  89

In [99]:
abc.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, karnataka to guj
Data columns (total 1 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   corona cases  5 non-null      int64
dtypes: int64(1)
memory usage: 80.0+ bytes


In [100]:
abc

corona cases
karnataka            23
Delhi                34
Maha                 56
Kera                 78
guj                  89

In [101]:
abc.describe() # descriptive stats

corona cases
count      5.000000
mean      56.000000
std       28.044607
min       23.000000
25%       34.000000
50%       56.000000
75%       78.000000
max       89.000000

In [102]:
abc

corona cases
karnataka            23
Delhi                34
Maha                 56
Kera                 78
guj                  89

In [105]:
abc['corona cases'] # columns

karnataka    23
Delhi        34
Maha         56
Kera         78
guj          89
Name: corona cases, dtype: int64

In [107]:
abc.loc['karnataka'] # row

corona cases    23
Name: karnataka, dtype: int64

In [75]:
abc.iloc[0]#row

corona cases    23
Name: karnataka, dtype: int64

In [110]:
abc

corona cases
karnataka            23
Delhi                34
Maha                 56
Kera                 78
guj                  89

In [111]:
abc.loc['karnataka']=43 # mutable

In [112]:
abc

corona cases
karnataka            43
Delhi                34
Maha                 56
Kera                 78
guj                  89

In [113]:
find out which state has cases more than 70?

SyntaxError: invalid syntax (<ipython-input-113-57d6e5a147e9>, line 1)

In [114]:
abc[abc['corona cases']>70]

corona cases
Kera            78
guj             89

In [115]:
# writing the final has 0.25

In [127]:
abc

corona cases
karnataka            23
Delhi                34
Maha                 56
Kera                 78
guj                  89

In [128]:
abc.index

Index(['karnataka', 'Delhi', 'Maha', 'Kera', 'guj'], dtype='object')

In [129]:
abc.values

array([[23],
       [34],
       [56],
       [78],
       [89]], dtype=int64)

In [130]:
abc

corona cases
karnataka            23
Delhi                34
Maha                 56
Kera                 78
guj                  89

In [131]:
abc.reset_index()

index  corona cases
0  karnataka            23
1      Delhi            34
2       Maha            56
3       Kera            78
4        guj            89

In [121]:
abc.set_index('corona cases')

Empty DataFrame
Columns: []
Index: [43, 34, 56, 78, 89]

In [132]:
abc=abc.reset_index()

In [133]:
abc

index  corona cases
0  karnataka            23
1      Delhi            34
2       Maha            56
3       Kera            78
4        guj            89

In [134]:
abc.columns

Index(['index', 'corona cases'], dtype='object')

In [135]:
abc['index'] # column

0    karnataka
1        Delhi
2         Maha
3         Kera
4          guj
Name: index, dtype: object

In [138]:
abc[['index','corona cases']]

index  corona cases
0  karnataka            23
1      Delhi            34
2       Maha            56
3       Kera            78
4        guj            89

In [139]:
abc

index  corona cases
0  karnataka            23
1      Delhi            34
2       Maha            56
3       Kera            78
4        guj            89

In [140]:
abc.iloc[0]

index           karnataka
corona cases           23
Name: 0, dtype: object

In [141]:
abc

index  corona cases
0  karnataka            23
1      Delhi            34
2       Maha            56
3       Kera            78
4        guj            89

In [142]:
marks

python   SQL
arti     49.0  23.0
amy      32.0  45.0
james    43.0  67.0
smith    45.0  89.0
poli      NaN   NaN

In [143]:
marks.sort_values('python')

python   SQL
amy      32.0  45.0
james    43.0  67.0
smith    45.0  89.0
arti     49.0  23.0
poli      NaN   NaN

In [ ]:
# per manent

In [ ]:
marks=marks.sort_values('python')

In [111]:
marks.sort_values('python',inplace=True)# make per

In [112]:
marks

python  SQL
amy        32   45
james      43   67
smith      45   89
arti       49   23

In [144]:
marks

python   SQL
arti     49.0  23.0
amy      32.0  45.0
james    43.0  67.0
smith    45.0  89.0
poli      NaN   NaN

In [145]:
marks.sort_values()
                 

TypeError: sort_values() missing 1 required positional argument: 'by'

In [146]:
marks

python   SQL
arti     49.0  23.0
amy      32.0  45.0
james    43.0  67.0
smith    45.0  89.0
poli      NaN   NaN

In [147]:
marks.sort_values('SQL')

python   SQL
arti     49.0  23.0
amy      32.0  45.0
james    43.0  67.0
smith    45.0  89.0
poli      NaN   NaN

In [148]:
marks.sort_index(ascending=False)

python   SQL
smith    45.0  89.0
poli      NaN   NaN
james    43.0  67.0
arti     49.0  23.0
amy      32.0  45.0

In [149]:
abc

index  corona cases
0  karnataka            23
1      Delhi            34
2       Maha            56
3       Kera            78
4        guj            89

In [150]:
abc.sort_index()

index  corona cases
0  karnataka            23
1      Delhi            34
2       Maha            56
3       Kera            78
4        guj            89

In [151]:
marks

python   SQL
arti     49.0  23.0
amy      32.0  45.0
james    43.0  67.0
smith    45.0  89.0
poli      NaN   NaN

In [155]:
marks['npv']=12

In [158]:
marks.loc['james']=45

In [159]:
marks

python   SQL  npv
arti     49.0  23.0   12
amy      32.0  45.0   12
james    45.0  45.0   45
smith    45.0  89.0   12
poli      NaN   NaN   12

In [160]:
marks2=pd.DataFrame({'eda':[13,13,13,13,13,13]},index=['poli','arti','amy','james','smith','pop'])
                                            

In [161]:
marks2

eda
poli    13
arti    13
amy     13
james   13
smith   13
pop     13

In [167]:
marks.append(marks2)

python   SQL   npv   eda
arti     49.0  23.0  12.0   NaN
amy      32.0  45.0  12.0   NaN
james    45.0  45.0  45.0   NaN
smith    45.0  89.0  12.0   NaN
poli      NaN   NaN  12.0   NaN
poli      NaN   NaN   NaN  13.0
arti      NaN   NaN   NaN  13.0
amy       NaN   NaN   NaN  13.0
james     NaN   NaN   NaN  13.0
smith     NaN   NaN   NaN  13.0
pop       NaN   NaN   NaN  13.0

In [165]:
marks

python   SQL  npv
arti     49.0  23.0   12
amy      32.0  45.0   12
james    45.0  45.0   45
smith    45.0  89.0   12
poli      NaN   NaN   12

In [ ]:
del 
del
add row
add col
for row
for column
multiple
stack-level 0 and level 1
unstack
melt
split
merge
concat
joinnn-outer,inner, left, right
drop dupli, keep last, keep first
read files
